from qt_core import *

class PyScrollArea(QScrollArea):
    def __init__(self):
        super().__init__()

        # SET STYLESHEET
        self.set_stylesheet()

    # SET STYLESHEET
    def set_stylesheet(self):
        self.setWidgetResizable(True)
        self.setStyleSheet(u"QScrollBar:vertical{\n"
"	border:none;\n"
"	background: rgb(45,45,68);\n"
"	width: 14px;\n"
"	margin: 15px 0 15px 0;\n"
"	border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"	background-color: rgb(80,80,122);\n"
"	min-height: 30px;\n"
"	border-radius:7px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"	border:none;\n"
"	background: rgb(45,45,68);\n"
"	height: 15px;\n"
"	border-top-left-radius: 7px;\n"
"	border-top-right-radius: 7px;\n"
"	subcontrol-position: top;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"	border:none;\n"
"	background: rgb(45,45,68);\n"
"	height: 15px;\n"
"	border-bottom-left-radius: 7px;\n"
"	border-bottom-right-radius: 7px;\n"
"	subcontrol-position: bottom;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"	background:none;\n"
"}\n"
"QScrollBar::sub-page:vertical, QScrollBar::add-page:vertical {\n"
"	background:none;\n"
"}QScrollBar:vertical{\n"
"	border:none;\n"
"	back"
                        "ground: rgb(45,45,68);\n"
"	width: 14px;\n"
"	margin: 15px 0 15px 0;\n"
"	border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"	background-color: rgb(80,80,122);\n"
"	min-height: 30px;\n"
"	border-radius:7px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"	border:none;\n"
"	background: rgb(45,45,68);\n"
"	height: 15px;\n"
"	border-top-left-radius: 7px;\n"
"	border-top-right-radius: 7px;\n"
"	subcontrol-position: top;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"	border:none;\n"
"	background: rgb(45,45,68);\n"
"	height: 15px;\n"
"	border-bottom-left-radius: 7px;\n"
"	border-bottom-right-radius: 7px;\n"
"	subcontrol-position: bottom;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"	background:none;\n"
"}\n"
"QScrollBar::sub-page:vertical, QScrollBar::add-page:vertical {\n"
"	background:none;\n"
"}")